# Generated by Django 4.1.5 on 2023-04-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('pswd', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=500)),
                ('utype', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
