# Generated by Django 4.1.5 on 2023-04-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesUnitapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('pswd', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=500)),
                ('img', models.ImageField(default='', upload_to='shops/')),
                ('licence_no', models.CharField(default='', max_length=100)),
                ('licenceid_img', models.ImageField(default='', upload_to='licence/')),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
