# Generated by Django 4.1.5 on 2023-04-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesUnitapp', '0002_tb_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(default='', upload_to='product/')),
                ('qty', models.CharField(default='', max_length=100)),
                ('mesure', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('discription', models.CharField(default='', max_length=500)),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
