# Generated by Django 4.1.5 on 2023-04-06 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesUnitapp', '0003_tb_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_product',
            name='shop_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesUnitapp.tb_shop'),
        ),
    ]
