# Generated by Django 4.1.5 on 2023-04-12 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesUnitapp', '0004_tb_product_shop_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesUnitapp.tb_register')),
            ],
        ),
    ]
