# Generated by Django 4.1.5 on 2023-04-13 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesUnitapp', '0006_tb_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_item_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('payment_status', models.CharField(default='', max_length=30)),
                ('packing_status', models.CharField(default='', max_length=30)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesUnitapp.tb_cart')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesUnitapp.tb_product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesUnitapp.tb_register')),
            ],
        ),
    ]
