# Generated by Django 4.1.5 on 2023-04-14 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesUnitapp', '0007_order_item_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('total_amt', models.CharField(default='', max_length=100)),
                ('card_name', models.CharField(default='', max_length=100)),
                ('card_number', models.CharField(default='', max_length=100)),
                ('card_cvv', models.CharField(default='', max_length=100)),
                ('card_expdate', models.CharField(default='', max_length=100)),
                ('pay_status', models.CharField(default='', max_length=100)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesUnitapp.order_item_tb')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesUnitapp.tb_product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesUnitapp.tb_register')),
            ],
        ),
    ]
