# Generated by Django 4.1.5 on 2023-04-21 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesUnitapp', '0008_tb_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesUnitapp.tb_product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesUnitapp.tb_register')),
            ],
        ),
    ]
