# Generated by Django 4.2.6 on 2023-11-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesUnitapp', '0009_tb_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('pswd', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
