# Generated by Django 4.2.6 on 2023-11-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesUnitapp', '0010_tb_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_admin',
            name='email',
            field=models.CharField(default='admin@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='tb_admin',
            name='pswd',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
