# Generated by Django 4.2.6 on 2023-11-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesUnitapp', '0011_alter_tb_admin_email_alter_tb_admin_pswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_admin',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tb_admin',
            name='pswd',
            field=models.CharField(default='', max_length=100),
        ),
    ]
