# Generated by Django 5.1.7 on 2025-07-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesUnitapp', '0012_alter_tb_admin_email_alter_tb_admin_pswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_register',
            name='utype',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
